apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scalping-bot
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: scalping-bot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-scalping-bot-config
        volumeMounts:
        - name: scalper-config
          mountPath: /app/config
          subPath: scalper.json
      volumes:
      - name: scalper-config
        configMap:
          name: {{ .Release.Name }}-scalping-bot-config
