apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-trader
  labels:
    app: test-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-trader
  template:
    metadata:
      labels:
        app: test-trader
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Inhoud van /trader:" && ls -la /trader
          echo "Inhoud van /connection:" && ls -la /connection
          cp -rL /trader/* /merged/ && cp -rL /connection/* /merged/
          echo "Inhoud van /merged:" && ls -la /merged
        volumeMounts:
        - name: trader-config
          mountPath: /trader
        - name: connection-config
          mountPath: /connection
        - name: merged-config
          mountPath: /merged

      containers:
      - name: bitvavo-trader
        image: bitvavo-trader:0.1.23
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        env: # Voeg hier eventueel andere environment variables toe
        volumeMounts:
        - name: merged-config
          mountPath: /app/config
        - name: data-volume
          mountPath: /app/data
        args:
        - "--config"
        - "/app/config/trader.json"
        ports:
        - containerPort: 8080
          name: http
      volumes:
      - name: trader-config
        configMap:
          name: trader-config
      - name: connection-config
        configMap:
          name: connection-config
      - name: merged-config
        emptyDir: {}
      - name: data-volume
        hostPath:
          path: /data # Pas dit pad aan naar jouw omgeving