apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitvavo-scalper
  labels:
    app: bitvavo-scalper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitvavo-scalper
  template:
    metadata:
      labels:
        app: bitvavo-scalper
    spec:
      containers:
      - name: bitvavo-scalper
        image: bitvavo-scalper:latest
        resources:
          limits:
            memory: "256Mi" # Maximum memory limit
            cpu: "500m" # Maximum CPU limit (half a core)
          requests:
            memory: "128Mi" # Minimum memory request
            cpu: "250m" # Minimum CPU request (quarter of a core)
        env:
        - name: BOT_NAME
          value: "bitvavo-scalper" # Unique bot name
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: data-volume
          mountPath: /app/data
        args:
        - "--config"
        - "/app/config/scalper.json" # Path to the config file
        ports:
        - containerPort: 8080
          name: http
      volumes:
      - name: config-volume
        hostPath:
          path: /path/to/your/config # Replace with your host path for configs
      - name: data-volume
        hostPath:
          path: /path/to/your/data # Replace with your host path for persistent data