replicaCount: 1

image:
  repository: your-docker-repo/bitvavo-scalper
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

config:
  scalperConfig: |
    {
      "PAIRS": ["TRUMP-EUR", "ETH-EUR", "SOL-EUR"],
      "TOTAL_BUDGET": 1000.0,
      "DAILY_TARGET": 50.0,
      "TRADING_PERIOD_HOURS": 12,
      "CHECK_INTERVAL": 60,
      "WINDOW_SIZE": 2,
      "TRADE_FEE_PERCENTAGE": 0.25,
      "STOP_LOSS_RETRY_COUNT": 3,
      "STOP_LOSS": -2.0,
      "THRESHOLD_BUY": -0.1,
      "THRESHOLD_SELL": 0.1,
      "DEMO_MODE": true,
      "USE_RSI": true
    }
